export type Role = "user" | "assistant" | "tool" | "system";

/** "trace" rows are intermediate agent breadcrumbs (tool-call hints,
 * progress pings) that should not be rendered as conversational replies. */
export type MessageKind = "message" | "trace" | "file_activity_cluster";

/** One per-call file-edit event from the agent runner; the cluster on
 * a ``UIMessage`` accumulates these by ``call_id`` and renders them as
 * chips. ``phase`` is the latest delivered for that call. */
export interface FileEditActivity {
  call_id: string;
  tool: string;
  path: string;
  phase: "start" | "end" | "error";
  status: "editing" | "done" | "error";
  added: number;
  deleted: number;
  approximate: boolean;
  binary: boolean;
  error?: string;
  /** ``Date.now()`` from when this activity was last updated. Drives the
   * pulse anim and lets a frozen cluster keep its sort order. */
  updatedAt: number;
}

/** One image attached to a UIMessage.
 *
 * ``url`` can arrive in three different shapes, which the bubble renders
 * identically:
 * - A ``data:image/...;base64,...`` URL generated by the Composer for the
 *   optimistic preview of an in-flight user turn. Self-contained, no
 *   lifecycle.
 * - A signed ``/api/media/...`` URL attached to a historical user turn by
 *   the backend on session replay. Safe to drop into an ``<img src>``.
 * - Absent. The backend couldn't resolve a stored path (file moved,
 *   deleted, or pre-media-persistence session). The bubble shows a
 *   placeholder tile with ``name`` as the label.
 */
export interface UIImage {
  url?: string;
  name?: string;
}

export interface UIMessage {
  id: string;
  role: Role;
  content: string;
  kind?: MessageKind;
  isStreaming?: boolean;
  createdAt: number;
  /** For trace rows: each individual hint line, so consecutive hints can
   * render as a single collapsible group. */
  traces?: string[];
  /** User turn: optimistic blob URLs for preview. Replay: placeholder chips. */
  images?: UIImage[];
  /** Milliseconds elapsed since send, ticked once a second on the in-flight
   * assistant placeholder until the first delta arrives. Cleared once the
   * stream begins so the bubble can render its content cleanly. */
  latencyMs?: number;
  /** File-edit cluster: present only on ``kind = "file_activity_cluster"``
   * rows. The collector folds activity events by ``call_id`` so the chip
   * cluster never renders duplicates. */
  activities?: FileEditActivity[];
}

export interface ChatSummary {
  /** Server-side session key, e.g. ``websocket:abcd-...``. */
  key: string;
  /** Local channel + chat_id parts derived from ``key`` for convenience. */
  channel: string;
  chatId: string;
  createdAt: string | null;
  updatedAt: string | null;
  preview: string;
  /** LLM-generated chat title, if the backend has summarized this session. */
  title?: string;
  pinned?: boolean;
  archived?: boolean;
  modelOverride?: string | null;
}

export interface SearchHit {
  sessionKey: string;
  messageIndex: number;
  role: string;
  snippet: string;
  /** Pairs of half-open offsets into ``snippet`` where the query matched. */
  matchOffsets: Array<[number, number]>;
  title: string;
  archived: boolean;
}

export interface SearchResponse {
  results: SearchHit[];
  offset: number;
  limit: number;
  hasMore: boolean;
}

export interface BootstrapResponse {
  token: string;
  ws_path: string;
  expires_in: number;
  model_name?: string | null;
}

export type ConnectionStatus =
  | "idle"
  | "connecting"
  | "open"
  | "reconnecting"
  | "closed"
  | "error";

export interface AdminConfigBackup {
  id: string;
  mtime_ms: number;
  size_bytes: number;
  source: string;
  kind: string;
  summary: Record<string, unknown>;
}

export interface AdminConfigMutationResult {
  path: string;
  restartRequired: boolean;
}

export interface AdminBindTestResult {
  ok: boolean;
  errno?: string;
  message?: string;
}

export interface AdminChannelTestResult {
  ok: boolean;
  checks: string[];
  last_error?: string | null;
  ms?: number;
}

export interface AdminMcpProbeResult {
  ok: boolean;
  tools: string[];
  elapsed_ms: number;
  error?: string;
}

export interface AdminBrowserProbeResult {
  active_contexts: number;
  last_url: string | null;
  cookie_size_bytes: number;
}

export type InboundEvent =
  | { event: "ready"; chat_id: string; client_id: string }
  | { event: "attached"; chat_id: string }
  | {
      event: "message";
      chat_id: string;
      text: string;
      reply_to?: string;
      media?: string[];
      /** Present when the frame is an agent breadcrumb (e.g. tool hint,
       * generic progress line) rather than a conversational reply. */
      kind?: "tool_hint" | "progress";
    }
  | {
      event: "delta";
      chat_id: string;
      text: string;
      stream_id?: string;
    }
  | {
      event: "stream_end";
      chat_id: string;
      stream_id?: string;
      /** True when this stream segment ended because the agent is continuing
       * into tools / another model turn, not because the whole turn is done. */
      resuming?: boolean;
    }
  | {
      event: "transcription_result";
      request_id: string;
      text: string;
    }
  | {
      event: "admin_config_saved";
      request_id?: string;
      path: string;
      restart_required?: boolean;
    }
  | {
      event: "admin_config_error";
      request_id?: string;
      path?: string;
      detail?: string;
    }
  | {
      event: "admin_test_bind_result";
      request_id?: string;
      result: AdminBindTestResult;
    }
  | {
      event: "admin_test_channel_result";
      request_id?: string;
      result: AdminChannelTestResult;
    }
  | {
      event: "admin_mcp_probe_result";
      request_id?: string;
      result: AdminMcpProbeResult;
    }
  | {
      event: "admin_browser_probe_result";
      request_id?: string;
      result: AdminBrowserProbeResult;
    }
  | {
      event: "webui_sidebar_state";
      request_id?: string;
      state: WebUISidebarState;
    }
  | {
      event: "webui_sidebar_state_error";
      request_id?: string;
      detail?: string;
    }
  | {
      event: "provider_failover";
      chat_id?: string;
      info: ProviderFailoverInfo;
    }
  | {
      event: "file_activity";
      chat_id: string;
      activity: FileActivityPayload;
    }
  | {
      event: "webui_file_read";
      request_id?: string;
      path: string;
      binary: boolean;
      content: string;
      size: number;
      truncated: boolean;
    }
  | {
      event: "webui_file_read_error";
      request_id?: string;
      detail?: string;
    }
  | { event: "error"; chat_id?: string; detail?: string; request_id?: string };

/** Wire shape emitted by ``runner.py`` for each file-edit phase. The hook
 * normalizes this into a ``FileEditActivity`` keyed by ``call_id``. */
export interface FileActivityPayload {
  version: 1;
  call_id: string;
  tool: string;
  path: string;
  phase: "start" | "end" | "error";
  status: "editing" | "done" | "error";
  added: number;
  deleted: number;
  approximate: boolean;
  binary: boolean;
  error?: string;
}

/** One-shot notice emitted by ``FallbackProvider`` when a primary model
 * failed mid-turn and a fallback took over. Surfaced as a dismissible
 * toast in the WebUI. */
export interface ProviderFailoverInfo {
  version: 1;
  primary: string;
  fallback: string;
  reason: string;
}

export type WebUISidebarDensity = "comfortable" | "compact";
export type WebUISidebarSort = "updated_desc" | "created_desc" | "title_asc";

/** Schema-v1 of the WebUI sidebar state delivered by the
 * ``webui_sidebar_state.get`` / ``.set`` envelopes (see
 * ``pythinker/webui/sidebar_state.py``). Pin/archive state lives in
 * per-session sidecars and is intentionally *not* consumed from this
 * payload here — sidecars remain the source of truth for those flags. */
export interface WebUISidebarState {
  schema_version: 1;
  pinned_keys: string[];
  archived_keys: string[];
  title_overrides: Record<string, string>;
  tags_by_key: Record<string, string[]>;
  collapsed_groups: Record<string, boolean>;
  view: {
    density: WebUISidebarDensity;
    show_previews: boolean;
    show_timestamps: boolean;
    show_archived: boolean;
    sort: WebUISidebarSort;
  };
  updated_at: string | null;
}

/** Base64-encoded image attached to an outbound ``message`` envelope.
 *
 * ``data_url`` must be a ``data:image/<png|jpeg|webp|gif>;base64,...`` string
 * — the server whitelists those MIME types and rejects everything else
 * (including SVG, to avoid an XSS surface). ``name`` is advisory: it's
 * preserved for the file on disk and surfaced as the placeholder label when
 * the session is replayed.
 */
export interface OutboundMedia {
  data_url: string;
  name?: string;
}

export type Outbound =
  | { type: "new_chat" }
  | { type: "attach"; chat_id: string }
  | {
      type: "message";
      chat_id: string;
      content: string;
      media?: OutboundMedia[];
    }
  | { type: "stop"; chat_id: string }
  | { type: "regenerate"; chat_id: string }
  | { type: "edit"; chat_id: string; user_msg_index: number; content: string }
  | { type: "set_model"; chat_id: string; model: string }
  | {
      type: "admin_config_set";
      request_id: string;
      path: string;
      value: unknown;
    }
  | {
      type: "admin_config_unset";
      request_id: string;
      path: string;
    }
  | {
      type: "admin_config_replace_secret";
      request_id: string;
      path: string;
      value: string;
    }
  | {
      type: "admin_config_restore_backup";
      request_id: string;
      backup_id: string;
    }
  | {
      type: "admin_test_bind";
      request_id: string;
      host: string;
      port: number;
    }
  | {
      type: "admin_test_channel";
      request_id: string;
      name: string;
    }
  | {
      type: "admin_mcp_probe";
      request_id: string;
      server: string;
    }
  | {
      type: "admin_browser_probe";
      request_id: string;
    }
  | {
      type: "transcribe";
      audio_base64: string;
      format: string;
      request_id: string;
    }
  | {
      type: "webui_sidebar_state.get";
      request_id: string;
    }
  | {
      type: "webui_sidebar_state.set";
      request_id: string;
      state: WebUISidebarState;
    }
  | {
      type: "webui_file_read.get";
      request_id: string;
      path: string;
    };
